### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by mtlynch** [nitronick600/sia3#2]
Love this project! Thanks for publishing the source.

Would it be possible to publish a `LICENSE` file specifying the open source license this is licensed under? Some developers have employment agreements that prevent them from contributing to open source projects unless they have particular licenses.

If you need help picking a license, check out https://choosealicense.com/

**Comment by nitronick600** [comment]
Thanks, forgot about that! 

6a911845f97ab9770c39f06e72fc08a36f945f56
